{
    parserClass="at.tewan.mcpc.language.mcfunction.parser.MCFunctionParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="MCFunction"
    psiImplClassSuffix="Impl"
    psiPackage="at.tewan.mcpc.language.mcfunction.psi"
    psiImplPackage="at.tewan.mcpc.language.mcfunction.psi.impl"

    elementTypeHolderClass="at.tewan.mcpc.language.mcfunction.psi.MCFunctionTypes"
    elementTypeClass="at.tewan.mcpc.language.mcfunction.psi.MCFunctionElementType"
    tokenTypeClass="at.tewan.mcpc.language.mcfunction.psi.MCFunctionTokenType"

    psiImplUtilClass="at.tewan.mcpc.language.mcfunction.psi.impl.MCFunctionPsiImplUtil"

}

mcfunctionFile ::= item_*

private item_ ::= (command|COMMENT|CRLF)

command ::= COMMAND_NAME ((COMMAND_ARGUMENT|TARGET_SELECTOR)?)+