{
    parserClass="at.tewan.mcpc.language.mcfunction.parser.MCFunctionParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="MCFunction"
    psiImplClassSuffix="Impl"
    psiPackage="at.tewan.mcpc.language.mcfunction.psi"
    psiImplPackage="at.tewan.mcpc.language.mcfunction.psi.impl"

    elementTypeHolderClass="at.tewan.mcpc.language.mcfunction.psi.MCFunctionTypes"
    elementTypeClass="at.tewan.mcpc.language.mcfunction.psi.MCFunctionElementType"
    tokenTypeClass="at.tewan.mcpc.language.mcfunction.psi.MCFunctionTokenType"

    psiImplUtilClass="at.tewan.mcpc.language.mcfunction.psi.impl.MCFunctionPsiImplUtil"

}

mcfunctionFile ::= (command|COMMENT|WHITE_SPACE)*


command ::= COMMAND_NAME (SPACE arg)* COMMAND_END
arg ::= COMMAND_ARGUMENT | target
target ::= TARGET_SELECTOR(TARGET_BODY_START WHITE_SPACE? TARGET_ATTR_KEY WHITE_SPACE? TARGET_ATTR_EQU WHITE_SPACE? TARGET_BODY_END)?